# الحصول على ملف تفعيل Unity (.alf) بدون كمبيوتر — يعمل داخل نفس صورة Docker المستخدمة للبناء.
#   1) Actions → "Request Unity activation file" → Run workflow
#   2) حمّل الـ Artifact (Unity_v6000.0.82f1.alf)
#   3) افتح https://license.unity3d.com/manual → ارفع الـ .alf → اختر Personal → حمّل ملف .ulf
#   4) افتح الـ .ulf كنص، وانسخ محتواه كله في Secret باسم UNITY_LICENSE
#      وأضف أيضاً UNITY_EMAIL و UNITY_PASSWORD (حساب Unity).
name: Request Unity activation file

on:
  workflow_dispatch:

jobs:
  alf:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.0.82f1-android-3
    steps:
      - name: Create manual activation file
        run: |
          unity-editor -batchmode -nographics -quit -logFile /dev/stdout -createManualActivationFile || true
          ls -la *.alf
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.0.82f1.alf
          path: Unity_v*.alf
          if-no-files-found: error
